App Health Extension v2: Support TLS 1.3
Azure/applicationhealth-extension-linux pull request #38
Opened 2023-09-06 00:09 UTC by klugorosado

- Included Support for TLS 1.3
- Minimum  TLS 1.1 enforced.

2023-09-06 18:00 UTC, frank-pang-msft commented on main/health.go
> +				MinVersion:         tls.VersionTLS11,
Not against specifying version, but I think today TLS version is probably automatically selected if we don't specify min/max versions. If TLS 1.4 comes out in the future we'll have to make the change again, do you think we should leave it that way or is there a benefit to specifying?

2023-09-06 18:10 UTC, frank-pang-msft commented on main/health.go
> +		transport = &http.Transport{
Does HTTP protocol use TLS, I think only HTTPS does?

2023-09-06 18:26 UTC, klugorosado commented on main/health.go
> +				MinVersion:         tls.VersionTLS11,
Honestly, it doesn't make much difference. When TLS 1.4 is released, we'll need to upgrade appHealth from GO 1.17 to the latest version anyway. The best way to future proof it is to upgrade to the latest GO version and not set a maxVersion.

2023-09-06 18:41 UTC, klugorosado commented on main/health.go
> +		transport = &http.Transport{
That is correct,but It wont throw error because HTTP will ignore TLS Config.
However I will still fix.

2023-09-15 19:15 UTC, frank-pang-msft approved these changes

2023-10-05 00:18 UTC, frank-pang-msft requested changes
Quick pass

2023-10-05 00:18 UTC, frank-pang-msft commented on integration-test/webserver/main.go
> +	tlsVersion := flag.String("tlsVersion", "tls1.3", "TLS version to use for https server. Options: 1.1, 1.2, 1.3")
nit not up to date.

Also, doens't really matter but maybe should we change arg name to something else since SSL is involved?

2023-10-05 00:18 UTC, frank-pang-msft commented on integration-test/webserver/main.go
> +func tlsVersionToUse(tlsVersion string) uint16 {
maybe securityProtocol instead of tlsVersion?

2023-10-05 00:18 UTC, frank-pang-msft commented on integration-test/test/test_helper.bash
> +    echo "DELETE: TEST_CONTAINER: $TEST_CONTAINER"
So this ensures that each container we spin up for each individual test gets deleted at the end?

2023-10-05 00:18 UTC, frank-pang-msft commented on integration-test/run.sh
> +sudo bats integration-test/test --jobs 10
For my own understanding, what does --jobs param indicate?

2023-10-05 00:18 UTC, frank-pang-msft commented on integration-test/test/2_handler-commands.bats
> +    container_name="${container_name}_1"
is there way in BATS framework to dynamically reference a testID? Adding suffix # manually can be tedious and if we ever decide to reorder these tests it can be a mess

2023-10-05 00:18 UTC, frank-pang-msft commented on .github/workflows/go.yml
> +        sudo apt install parallel
What is parallel? Also I recall BATS framework mentioned something about parallel execution of tests, is that not the case?

2023-10-05 00:57 UTC, klugorosado commented on .github/workflows/go.yml
> +        sudo apt install parallel
Parallel package is a requirement for parallel execution of bats test with the --jobs flag.

2023-10-05 01:05 UTC, klugorosado commented on integration-test/run.sh
> +sudo bats integration-test/test --jobs 10
The --jobs parameter indicates the max number of parallel processes to use. [Source](https://bats-core.readthedocs.io/en/stable/usage.html#parallel-execution:~:text=0.039%22%20/%3E%0A%3C/testsuite%3E%0A%3C/testsuites%3E-,Parallel%20Execution,-%C2%B6)

2023-10-05 01:07 UTC, klugorosado commented on integration-test/test/test_helper.bash
> +    echo "DELETE: TEST_CONTAINER: $TEST_CONTAINER"
This was used for debugging, I will remove this.

2023-10-05 05:10 UTC, rareddaz commented on main/health.go
> +				MaxVersion:         tls.VersionTLS13,
Do we need to specify min and max version here? Can we leave it to default?

2023-10-05 16:38 UTC, frank-pang-msft commented on integration-test/test/test_helper.bash
> +    echo "DELETE: TEST_CONTAINER: $TEST_CONTAINER"
So will each container thatis spinned up per test get deleted at the end?

2023-10-05 16:39 UTC, frank-pang-msft commented on integration-test/test/2_handler-commands.bats
> +    container_name="${container_name}_1"
If container name doesn't really matter, we could put this step in setup() since i think it runs each time?

2023-10-05 17:46 UTC, klugorosado commented on main/health.go
> +				MaxVersion:         tls.VersionTLS13,
Since we Have the Integration Tests in place, I think is safe to do so.

2023-10-06 17:18 UTC, klugorosado commented on main/health.go
> +				MaxVersion:         tls.VersionTLS13,
I attempted to leave defaults and the integration tests did not pass. This is because the Builds are on Go 1.20 which have default inversion TLS 1.2. In this case it's better to specify the min and max Versions to ensure combability.

2023-10-06 17:19 UTC, klugorosado commented on integration-test/test/test_helper.bash
> +    echo "DELETE: TEST_CONTAINER: $TEST_CONTAINER"
Yes, I added logic to handle that.

2023-10-07 00:01 UTC, frank-pang-msft commented on main/health.go
> +				MaxVersion:         tls.VersionTLS13,
If we omit Min and Max version shouldn’t the app use the same version that the application uses?

2023-10-23 21:55 UTC, frank-pang-msft commented on main/health.go
> +				MinVersion:         tls.VersionTLS10,
Can we add a comment here specifying why we specify min version but not max?

I believe it's because in Go 1.18 all http clients default to TLS 1.2, but to support all TLS protocols before that we do 1.0. Is that right?

2023-10-23 21:58 UTC, frank-pang-msft commented on integration-test/run.sh
> +sudo bats integration-test/test/1_basic.bats && sudo bats $(find integration-test/test/ -type f -name "*.bats" ! -name "1_basic.bats") --jobs 10
Just as a sanity check, I think there is a way to run the tests with verbose logs.

Have you confirmed that the tests are executing entirely and are not just passing due to returning early?

2023-11-08 07:33 UTC, klugorosado commented
This pull request includes a variety of changes to improve the functionality and usability of the codebase. The most important changes include adding new tests to the `integration-test` directory, adding support for tls1.0 and trimming leading slashes in the request path, and updating multiple scripts to use a custom container name instead of a hardcoded value.

Main interface changes:

* <a href="diffhunk://#diff-2422cb6e5f570a2a3eeb5388f7e0fcc644727dfd0d34911de35e83a268f1d2efL132-R144">`main/health.go`</a>: Added support for tls1.0, trimmed leading slashes in the request path, and removed an unnecessary line in the `NewHealthProbe` function. 
* <a href="diffhunk://#diff-678682767f2477de3e3c546746f8568b9a1942b2c647d32331d7e774b8ff8d9fR51-R54">`.github/workflows/go.yml`</a>: Added three new jobs for integration testing, including sequential and parallel testing with retrying failed tests.

Testing improvements:

* <a href="diffhunk://#diff-db5ccf1b6f97761a2e7e8cb4c16754861128734a0bda7520aa4b7d51b530cbe2R9-R57">`integration-test/test/test_helper.bash`</a>: Added new functions to clean up Docker containers and images after running tests, as well as create and delete self-signed certificates for testing purposes. 
* <a href="diffhunk://#diff-8aa2da999d8c499c37122550a034e558ff32fbfd4a1683a13c59c1ba7b1d636dR7-R16">`integration-test/test/4_grace-period.bats`</a>: Added functionality to the `integration-test/test/4_grace-period.bats` script, including sourcing a helper file, using a custom container name, and replacing hardcoded values with variables. 
* <a href="diffhunk://#diff-554f373b1ba296bbbf5403dcfafb077c73217421e8bdc9a349d4ba8e33c2e8cbR7-R16">`integration-test/test/2_handler-commands.bats`</a>: Updated multiple tests in `integration-test/test/2_handler-commands.bats` to use a custom container name instead of the hardcoded value `sh`. 
* <a href="diffhunk://#diff-490ae6b7f1640e574ff99e742a2bffc435826700e81cea1a73f54ed224fd43fdL47-R49">`integration-test/test/5_custom-metrics.bats`</a>: Updated multiple tests in `integration-test/test/5_custom-metrics.bats` to use a custom container name instead of hardcoded container names. 
* `integration-test/test/3_rich-states.bats`: Introduced a variable `$container_name` to ensure consistency in the container name used throughout the `3_rich-states.bats` script. 
* <a href="diffhunk://#diff-102558af691a84d712ba881d170810ddac31f5b56b409e1dec2bd2cf0431cfdbR1-R206">`integration-test/test/6_tls-config.bats`</a>: Added new test file `integration-test/test/6_tls-config.bats` to test SSL/TLS protocols supported by the webserver.

Other changes:

* <a href="diffhunk://#diff-81c362d167240c77cd39a0678f9bf4de3b93ecd0a7ed07c5eb780173530532ecL41-R41">`integration-test/README.md`</a>: Updated to use the `run.sh` script instead of running the `bats` command directly.
* <a href="diffhunk://#diff-ace417b47e816a44cf3b6f6248e72453a46d9e6043f19aea9d39212e852cc373L5-R11">`main/cmds.go`</a>: Added three import statements for later use.
* Re-target Pull Request to develop/v2 to follow GitFlow.

2023-11-08 17:01 UTC, Hafthor commented on integration-test/test/6_tls-config.bats
> +    [[ "$output" == *'No longer honoring grace period - expired'* ]]
what do these lines do? maybe add a comment.

2023-11-08 20:15 UTC, klugorosado commented on main/health.go
> +				MinVersion:         tls.VersionTLS10,
comment added

2023-11-08 21:16 UTC, klugorosado commented on main/health.go
> +	p.Address = fmt.Sprintf("%s://localhost%s/%s", protocol, portString, requestPath)
ack

2023-11-08 21:18 UTC, klugorosado commented on integration-test/test/test_helper.bash
> +        local random_number=$((1 + RANDOM % 1000000))
ack

2023-11-08 21:24 UTC, frank-pang-msft commented on .github/workflows/go.yml
> +    - name: Run Integration Tests in Parallel
"Run Parallel Integration Tests"

2023-11-08 21:24 UTC, frank-pang-msft commented on .github/workflows/go.yml
> +    - name: Run Integration Tests Sequentially
Run Sequential Integration Tests

2023-11-08 21:25 UTC, frank-pang-msft commented on .github/workflows/go.yml
> +    - name: Retry Failing Integration Tests
If Sequential and Parallel tests failed, is that okay? Maybe there should be separate steps for retry sequential and retry parallel?

sequential
retry sequential
parallel
retry parallel

2023-11-08 21:51 UTC, klugorosado commented on .github/workflows/go.yml
> +    - name: Retry Failing Integration Tests
Since this step is to re-test Flaky tests it not necessary to run them in parallel. Normally there is one Flaky test per run (the last to complete) not sure why.

2023-11-08 23:53 UTC, klugorosado commented on integration-test/test/test_helper.bash
> +    if [ -n "$(docker images -q $IMAGE)" ]; then
ack

2023-11-08 23:53 UTC, klugorosado commented on integration-test/test/6_tls-config.bats
> +    [[ "$output" == *'No longer honoring grace period - expired'* ]]
ack

2023-11-08 23:54 UTC, klugorosado commented on .github/workflows/go.yml
> +    - name: Run Integration Tests Sequentially
ack

2023-11-08 23:54 UTC, klugorosado commented on .github/workflows/go.yml
> +    - name: Run Integration Tests in Parallel
ack

2023-11-09 02:39 UTC, klugorosado commented on integration-test/test/6_tls-config.bats
> +    [[ "$output" == *'No longer honoring grace period - expired'* ]]
This test verifies the situation where only SSLv3, or outdated and insecure security protocol, is required by the Customers App. New comments have been added.

2023-11-09 02:55 UTC, klugorosado commented on integration-test/run.sh
> +sudo bats integration-test/test/1_basic.bats -T --trace
Good recommendation

2023-11-09 12:34 UTC, Hafthor commented on integration-test/test/6_tls-config.bats
> +    [[ "$output" == *'No longer honoring grace period - expired'* ]]
whoops. looks like we have duplicate lines here

2023-11-09 12:34 UTC, Hafthor commented on main/health.go
> +	requestPath = strings.TrimPrefix(requestPath, "/")
nit: url.URL already trims leading / from Path

2023-11-09 12:34 UTC, Hafthor commented on main/health_test.go
> +	requestPath := "/test"
maybe make a couple of these tests with "test" as the requestPath to test "/" trimming

2023-11-09 12:34 UTC, Hafthor commented on integration-test/webserver/main.go
> +	}
nit: return the captured healthState

    if healthState, ok := healthStateFlagMapping[flag]; ok {
        return healthState
    } else {
        return ""
    }

2023-11-09 19:57 UTC, klugorosado commented on integration-test/test/6_tls-config.bats
> +    [[ "$output" == *'No longer honoring grace period - expired'* ]]
No sure how this happened.

2023-11-09 20:25 UTC, klugorosado commented on main/health_test.go
> +	requestPath := "/test"
ack

2023-11-09 20:37 UTC, klugorosado commented on main/health.go
> +	requestPath = strings.TrimPrefix(requestPath, "/")
Left it because the documentation says "may omit leading slash" but will change.

2023-11-15 19:15 UTC, frank-pang-msft commented on .github/workflows/go.yml
> +    - name: Retry Failing Integration Tests
I guess it's fine, but I noticed in the github actions, sequential and parallel tests do not fail, but the retry step still executes?

2023-11-15 19:23 UTC, Hafthor approved these changes

2023-11-15 21:08 UTC, klugorosado commented on .github/workflows/go.yml
> +    - name: Retry Failing Integration Tests
just fixed the problem

2023-11-15 21:11 UTC, frank-pang-msft approved these changes

2023-11-15 21:12 UTC, frank-pang-msft commented
Can you update PR description with the latest?

2023-11-16 01:31 UTC, merged