Resource governance, heartbeat and dev container changes
Azure/applicationhealth-extension-linux pull request #43
Opened 2023-11-15 06:17 UTC by dpoole73

The main feature change here is the addition of resource governance for linux via cgroups.

We discover the current cgroup and add a sub cgroup for our purposes (limiting cpu to 1% and memory to 40MB)

I also added support for detecting a stuck vmwatch using the heartbeat file and implemented the same logic for restarts from the windows version (3 restarts per 3 hours)

As part of the development of this, I added support for devcontainer execution so we can step through the code from a dev machine into either a WSL session or a linux vm with tools installed.

I added integration tests to check process exit, OOM and cpu throttling.  These changes required a few changes to the makefile and scripts.

I also updated the vmwatch binaries and added a script to download the latest ones as well

I updated the govendor files using the tool it told me to run I hope I did this right

2023-11-16 17:28 UTC, frank-pang-msft reviewed
Forgot to submit last night, but this should be a good 1st pass

2023-11-16 17:28 UTC, frank-pang-msft commented on main/vmWatch.go
> +	NotRunning VMWatchStatus = "NotRunning"
For "NotRunning" should we have StatusWarning instead of StatusSuccess? See GetStatusType below

2023-11-16 17:28 UTC, frank-pang-msft commented on main/vmWatch.go
> +	// max 1% of cpu and 40MB of memory should be more than enough
I think in Windows it was 2% CPU and 50MB, do we want to keep them consistent?

2023-11-16 17:41 UTC, frank-pang-msft commented on main/vmWatch.go
> +			vmWatchResultChannel <- VMWatchResult{ Status: Failed, Error: vmWatchErr }
This makes VMWatch substatus in Failed state on each process exit. In Windows I think we have Failed state when we exceed the max attempts.

I forget though. For Windows is it also 1 retry every 1 hour up to 3 times, and then it will backoff?

2023-11-16 18:02 UTC, dpoole73 commented on .vscode/extensions.json
> +    "recommendations": [
good idea.

2023-11-16 18:09 UTC, dpoole73 commented on go.mod
>  	github.com/Azure/azure-docker-extension v0.0.0-20160802215703-0dd2f199467d
yeah i forget exactly what it told me to run it was some go vendor command.  I'm no expert on this stuff so whatever you want me to do I can do,  if removing vendor is the way to go I'm happy to do that

2023-11-16 18:12 UTC, dpoole73 commented on integration-test/test/7_vmwatch.bats
> +
yes, there's no specific trace for OOM since it is os killing it, so it is just killed

2023-11-16 18:23 UTC, dpoole73 commented on main/vmWatch.go
> +	NotRunning VMWatchStatus = "NotRunning"
good point

2023-11-16 18:25 UTC, dpoole73 commented on main/vmWatch.go
> +	// max 1% of cpu and 40MB of memory should be more than enough
I think I saw some spec that we wanted to keep under 1, I think I'll change the windows one to be in sync with this instead

2023-11-16 18:48 UTC, dpoole73 commented on main/vmWatch.go
> +	// max 1% of cpu and 40MB of memory should be more than enough
https://msazure.visualstudio.com/DefaultCollection/One/_git/Compute-ART-ManagedServiceExtensions/pullrequest/9104959

2023-11-17 04:52 UTC, dpoole73 commented on go.mod
>  	github.com/Azure/azure-docker-extension v0.0.0-20160802215703-0dd2f199467d
i think we can leave as is for now

2023-11-17 04:53 UTC, dpoole73 commented on main/vmWatch.go
> +		return "VMWatch is not running"
this will be a temp state right before it has started up, I don't think it will affect anything, based on conversations today we will leave as is

2023-11-17 09:10 UTC, klugorosado requested changes
Initial Pass, Still have files to Review

2023-11-17 09:12 UTC, klugorosado commented
We should make sure the GitHub Workflow is running.

2023-11-17 19:52 UTC, klugorosado commented on main/main.go
> +		killVMWatch(ctx, vmWatchCommand)
this was here before your PR, but we should probably handle the error. 
```suggestion
		killVMWatch(ctx, vmWatchCommand)
```

2023-11-17 19:52 UTC, klugorosado commented on main/vmWatch.go
>  )
We should probably move this to a different file for an easier migration of GHP.

2023-11-17 19:52 UTC, klugorosado commented on main/vmWatch.go
> +}
We should also move the Heartbeat to another file for easier migration/refactoring later, what do you think?

2023-11-17 19:52 UTC, klugorosado commented on main/vmWatch.go
> +	}
is this for testing only?

2023-11-17 19:52 UTC, klugorosado commented on main/vmWatch.go
> +func createAndAssignCgroups(vmWatchPid int) error {
Is this VMWatch specific Cgroup or can it be used for AppHealth if needed? 
Not sure becaue of the "cgroups.StaticPath(cpuPath+"/vmwatch.slice")"

2023-11-17 19:52 UTC, klugorosado commented on Makefile
> +devcontainer: binary testenv
can you add in the README how to run and test with the new Dev Container Changes?

2023-11-17 20:04 UTC, dpoole73 commented on main/vmWatch.go
> +	}
RUNNING_IN_DEV_CONTAINER will be set when using dev container for development and we can also use it to tell apop healthe extension to launch with --local in other scenarios to avoid vmwatch trying to talk to IMDS.

2023-11-17 20:09 UTC, dpoole73 commented on Makefile
> +devcontainer: binary testenv
which readme would you like me to update?

2023-11-20 18:19 UTC, dpoole73 commented on main/vmWatch.go
> +}
i don't really see the need right now.  I'd rather keep things specific to vmwatch for the current code base, feel free to move the code around when you create the GHP code base

2023-11-20 18:20 UTC, dpoole73 commented on main/vmWatch.go
> +func createAndAssignCgroups(vmWatchPid int) error {
i did some testing over the weekend and it varies by os but it works in all cases so far

2023-11-20 18:22 UTC, dpoole73 commented on integration-test/run.sh
> +sudo bats integration-test/test/$1
this was just added to allow for narrowing execution to a specific bats file, I'm guessing ththis is less critical now that the tests run in parallel and run much quicker

2023-11-21 04:51 UTC, frank-pang-msft commented on Makefile
> +devcontainer: binary testenv
I think adding README in .devcontainer directory would be good

2023-11-21 06:12 UTC, dpoole73 commented on integration-test/env/get-avg-vmwatch-cpu.sh
I've made it generic now

2023-11-21 06:17 UTC, dpoole73 commented on main/vmWatch.go
>  )
since this is currently vmwatch specific I feel like it's ok to leave where it is.  if you disagree can you suggest a restructring?

2023-11-21 06:44 UTC, dpoole73 commented on Makefile
> +devcontainer: binary testenv
done

2023-11-29 23:20 UTC, frank-pang-msft approved these changes
Some minor nits, but approved

2023-11-29 23:20 UTC, frank-pang-msft commented on .devcontainer/README.md
> +1. Got to the root of the repo in a command window
nits heree, but i think the bullet point formatting is odd. Is it using numbering instead of '-'

2023-11-30 00:30 UTC, klugorosado approved these changes
Few comments, but overall looks good

2023-11-30 00:30 UTC, klugorosado commented on Makefile
> +
Is this for the Dev Container?

2023-11-30 00:30 UTC, klugorosado commented on .devcontainer/README.md
> +# Dev Container Info
Can you also add documentation in /integration-test/README and Update the steps of running the tests?

2023-11-30 01:21 UTC, dpoole73 commented on integration-test/env/Extension/bin/upload-zip.sh
> +# this is a helper script to upload the latest binaries for app health extension and vmwatch to a zip file
we discussed and I think putting it somewhere else wouldn't make sense.  There is no risk exposing these things since you have to be authenticated to see them so this seems fine for now

2023-11-30 01:31 UTC, dpoole73 commented on .devcontainer/README.md
where is the typo?

2023-11-30 02:00 UTC, dpoole73 commented on Makefile
> +
this is not actually needed it was from a previous approach, removing

2023-11-30 02:02 UTC, dpoole73 commented on integration-test/env/Extension/bin/upload-zip.sh
> +az storage blob upload --account-name vmwatchtest --subscription 3f3e281a-dc49-4930-b5cf-7ac71cd31603 --container-name linux --name vmwatch.zip --file /tmp/vmwatch.zip
yes we dicussed and there's no issue here.  This is temporary and will go away once franks work is done (I hope)

2023-11-30 02:48 UTC, klugorosado commented on .devcontainer/README.md
"luanch.json"

2023-11-30 18:16 UTC, klugorosado approved these changes

2023-12-01 02:38 UTC, merged