Fixing bug to successfully kill AppHealth Gracefully & VMWatch.
Azure/applicationhealth-extension-linux pull request #59
Opened 2024-03-18 19:45 UTC by klugorosado

Changes by @klugorosado 
- Added Integration tests to kill AppHealth Gracefully with SIGTERM and SIGINT, and validated VMWatch Shutdown. 
- Added Integration tests to kill AppHealth Forcibly with SIGKILL, and validated VMWatch Shutdown. 
- Added the capability for dev containers to run Integration tests inside.

2024-03-18 20:05 UTC, frank-pang-msft requested changes
Looks good, just nits.

2024-03-18 20:05 UTC, frank-pang-msft commented on integration-test/env/extension-test-helpers.sh
> +    # echo "Checking if the AppHealth Extension and VMWatch are running"
nit: print statement commented out?

2024-03-18 20:05 UTC, frank-pang-msft commented on integration-test/env/extension-test-helpers.sh
> +    echo "Killing the applicationhealth extension forcefully" > /var/log/azure/Extension/force-kill-extension.txt
maybe not as familiar with bash, is it possible to declare this path as a variable and reference it instead?

2024-03-18 20:05 UTC, frank-pang-msft commented on main/vmWatch.go
> +	vmWatchCommand.SysProcAttr = &syscall.SysProcAttr{ Pdeathsig: syscall.SIGTERM }
Not PR blocking, but for `Pdeathsig: syscall.SIGTERM` , seems like it's sufficient, but wondering if other signals have different behavior? Dave and I just randomly tried this one

2024-03-18 20:13 UTC, dpoole73 approved these changes

2024-03-18 20:14 UTC, klugorosado commented on integration-test/env/extension-test-helpers.sh
> +    # echo "Checking if the AppHealth Extension and VMWatch are running"
ack

2024-03-18 20:20 UTC, klugorosado commented on integration-test/env/extension-test-helpers.sh
> +    echo "Killing the applicationhealth extension forcefully" > /var/log/azure/Extension/force-kill-extension.txt
ack

2024-03-19 01:06 UTC, klugorosado commented on main/vmWatch.go
> +	vmWatchCommand.SysProcAttr = &syscall.SysProcAttr{ Pdeathsig: syscall.SIGTERM }
`syscall.SIGTERM`, `syscall.SIGINT` and `syscall.SIGKILL` all work fine, I suppose it depends how VMWatch want to handle it.

2024-03-19 15:01 UTC, dpoole73 commented on main/vmWatch.go
> +	vmWatchCommand.SysProcAttr = &syscall.SysProcAttr{ Pdeathsig: syscall.SIGTERM }
I think you can only specify one right?  According to the docs, SIGKILL is the real abrupt kill (kill -9) SIGTERM is 15 which is still abrupt but does give some chance for the process to react.  When you say they all work do you mean that the tests still pass with each value specified here?  I'm not sure what the right value is

2024-03-19 16:14 UTC, dpoole73 commented on main/vmWatch.go
> +	vmWatchCommand.SysProcAttr = &syscall.SysProcAttr{ Pdeathsig: syscall.SIGTERM }
ah i think i follow now.  it is the signal that will be sent to the child process.  Yes SIGTERM is fine here

2024-03-19 19:04 UTC, frank-pang-msft approved these changes

2024-03-19 19:06 UTC, merged