Implementing New Sequence Number Management and Fixing how we get the extension Sequence Number
Azure/applicationhealth-extension-linux pull request #83
Opened 2024-06-11 21:56 UTC by klugorosado

This pull request includes changes to the sequence number management and testing in the `main` and `internal/seqno` packages. The most important changes include the creation of a new `SequenceNumberManager` interface and `SeqNumManager` struct, the addition of a function to check if a sequence number has already been processed before enabling it, and the addition of tests for the new function.

New sequence number management:

* [`internal/seqno/seqno.go`](diffhunk://#diff-f671e4abbca7ae7b738bc8ef287fcbf3995062b2cc5e54ad666e3fa6f1b674dcR1-R101): Created a new `SequenceNumberManager` interface and `SeqNumManager` struct to manage sequence numbers. The `SeqNumManager` struct includes functions to get and set sequence numbers, and to find a sequence number from either the environment variable or the most recently used file under the config folder.

Changes to `main` package:

* [`main/cmds.go`](diffhunk://#diff-ace417b47e816a44cf3b6f6248e72453a46d9e6043f19aea9d39212e852cc373L32-R32):  a new function `enablePre` has been added. This function, acting as the PreFunc for the enable command, verifies if the sequence number is ready for processing by comparing it with the last executed number from the `mrseq` file. This ensures orderly processing of sequence numbers.
* [`main/main.go`](diffhunk://#diff-327181d0a8c5e6b164561d7910f4eeffd41442d55b2a2788fda2aa2692f17ec0L64-R68): Replaced the `FindSeqNum` function with `seqnoManager.FindSeqNum` to find the sequence number.
* [`main/seqnum.go`](diffhunk://#diff-171d8d31093fac5a89b9bbe034fe628faf47dd12fad91b3205433ca95c56be52L1-L32): Removed the `FindSeqNum` function as it has been replaced by `seqnoManager.FindSeqNum`.

New tests:

* [`main/cmds_test.go`](diffhunk://#diff-bdb35e68cc43b04f7c8b572233a1472169052b84e0b471c6fe578fe049784223R36-R133): Added tests for the enablePre.

2024-06-13 19:57 UTC, klugorosado commented
retargeting to master

2024-06-13 21:39 UTC, dpoole73 approved these changes

2024-06-13 23:56 UTC, frank-pang-msft requested changes
First pass

2024-06-13 23:56 UTC, frank-pang-msft commented on main/cmds.go
> +	// If the most recent sequence number is greater than or equal to the requested sequence number,
I think we should allow running the same sequence number, e.g. what if mrSeqNum=5, and VM was restarted? seqNum would be run with 5 again and this will reject it

2024-06-13 23:56 UTC, frank-pang-msft commented on internal/seqno/seqno.go
> +	return int(seqNum), err
we can leave it as a `uint`, as that's a better representation of the sequence number than what we had before

2024-06-13 23:56 UTC, frank-pang-msft commented on internal/seqno/seqno.go
> +	GetCurrentSequenceNumberFunc func(lg log.Logger, name, version string) (int, error)
I'm finding it a little difficult to follow through this file. I'm not sure if we need an interface and then a class that implements the interface only to have it's own functions also being assigned a function.

Is there a reason why we need to have a class that contains methods? as opposed to just implementing the method directly into the class and also without an interface?

2024-06-13 23:56 UTC, frank-pang-msft commented on internal/seqno/seqno.go
> +	GetCurrentSequenceNumberFunc func(lg log.Logger, name, version string) (int, error)
I suggest only creating/nesting methods only if it makes it easier to read

2024-06-13 23:56 UTC, frank-pang-msft commented on internal/seqno/seqno.go
> +	lg := logging.NewNopLogger()
Any way we can use a logger that still logs to standard out or standard error? Otherwise all the logs inside the extension platform package will be omitted

2024-06-13 23:56 UTC, frank-pang-msft commented on internal/seqno/seqno.go
> +func SetSequenceNumber(extName, extVersion string, seqNo int) error {
it's okay to change seqNo to uint

2024-06-18 22:04 UTC, klugorosado commented on internal/seqno/seqno.go
> +	lg := logging.NewNopLogger()
that was my intention, to avoid catching the logs from the library. Its better if we control our own logs

2024-06-18 22:29 UTC, klugorosado commented on internal/seqno/seqno.go
> +	GetCurrentSequenceNumberFunc func(lg log.Logger, name, version string) (int, error)
Yes, The use of interfaces is intentional for few reasons:
- **Decoupling**: By using interfaces, we can decouple our code from specific implementations, which makes it easier to modify or replace components without affecting the rest of the system.
- **Testing**: Interfaces allow us to mock implementations, simplifying the process of writing tests without having to write a new bats-core unit test.

However, I found out another way to mock this interface in our UTs, so I cleaned up the file quite a bit.

2024-06-19 20:45 UTC, frank-pang-msft approved these changes

2024-06-19 22:54 UTC, frank-pang-msft commented on internal/seqno/seqno.go
> +	lg := logging.NewNopLogger()
Sounds good. Lets not merge this in master yet in case we need to cut a prod ext build

2024-06-28 01:13 UTC, merged