Record app health heartbeat + default ExtensionEvent OperationId to VMWatchCohortId
Azure/applicationhealth-extension-linux pull request #93
Opened 2024-11-14 23:43 UTC by frank-pang-msft

Record app health heartbeat + default ExtensionEvent OperationId to VMWatchCohortId

2024-11-15 00:30 UTC, frank-pang-msft commented on internal/telemetry/telemetry.go
> +		instance.eem.SetOperationID(uuid.New().String())
@zmyzheng 
It seems we never initialized OperationId for Linux, for parity with Windows I added this. 

I could remove it entirely.

2024-11-19 05:13 UTC, klugorosado requested changes

2024-11-19 05:13 UTC, klugorosado commented on main/cmds.go
> +			telemetry.SendEvent(telemetry.ErrorEvent, telemetry.AppHealthTask, "Error while getting VMWatchCohortId", "error", err)
use Telemetry.SetupVMWatchTask or another TaskName

2024-11-19 05:13 UTC, klugorosado commented on main/cmds.go
> +		// Since we only log health state changes, it is possible there will be no recent logs for app health extension.
This will work; however, I would create a go routine with the time ticker to log the event. I will be more consistent

2024-11-19 20:35 UTC, klugorosado commented on main/cmds.go
> +			telemetry.SendEvent(telemetry.ErrorEvent, telemetry.AppHealthTask, "Error while getting VMWatchCohortId", "error", err)
nevermind

2024-11-20 00:22 UTC, klugorosado approved these changes

2024-11-20 01:32 UTC, zmyzheng approved these changes

2024-11-20 01:39 UTC, merged